astronomy-commons/lsdb

docs/conf.py, pyproject.toml, src/.pylintrc, src/lsdb/catalog/dataset/dataset.py, src/lsdb/io/parquet_io.py, src/lsdb/loaders/hipscat/hipscat_catalog_loader.py, src/lsdb/loaders/hipscat/hipscat_loader_factory.py, src/lsdb/loaders/hipscat/read_hipscat.py, src/lsdb/loaders/hipscat/read_hipscat.pyi, tests/.pylintrc, tests/lsdb/catalog/test_catalog.py, tests/lsdb/loaders/hipscat/test_read_hipscat.py
- Extends black's line length to 110
- Run `black .` and `isort .`
- Adjust pylint allowable line length
=> Mechanical application of 110 line length.

src/lsdb/catalog/catalog.py, tests/lsdb/catalog/test_catalog.py, tests/lsdb/catalog/test_cone_search.py, tests/lsdb/loaders/hipscat/test_read_hipscat.py
Adds utility method to the LSDB catalog to access HEALPix pixels from the underlying HiPSCat catalog. The method was named `get_pixels` instead of `get_healpix_pixels` to keep the convention already in use by HiPSCat. Closes #21.
=> Method to get HEALPix pixels from Catalog

benchmarks/benchmarks.py, src/lsdb/catalog/catalog.py, src/lsdb/core/cone_search.py, src/lsdb/loaders/hipscat/hipscat_catalog_loader.py, tests/lsdb/catalog/test_catalog.py, tests/lsdb/catalog/test_cone_search.py, tests/lsdb/loaders/hipscat/test_read_hipscat.py
In preparation for addressing https://github.com/astronomy-commons/hipscat/issues/142, this removes the `get_pixels` method in favor of a `get_healpix_pixels` method to mirror what will be available on the `Catalog` API.
=> Re-factor get_pixels

cloud_tests/conftest.py, cloud_tests/copy_data_to_fs.py, cloud_tests/lsdb/catalog/test_catalog.py, cloud_tests/lsdb/catalog/test_cone_search.py, cloud_tests/lsdb/catalog/test_crossmatch.py, cloud_tests/lsdb/loaders/hipscat/test_read_hipscat.py, src/lsdb/loaders/dataframe/dataframe_catalog_loader.py, src/lsdb/loaders/dataframe/from_dataframe.py, src/lsdb/loaders/hipscat/hipscat_catalog_loader.py, src/lsdb/loaders/hipscat/hipscat_loader_factory.py, src/lsdb/loaders/hipscat/read_hipscat.py, src/lsdb/loaders/hipscat/read_hipscat.pyi, tests/lsdb/catalog/test_crossmatch.py, tests/lsdb/loaders/dataframe/test_from_dataframe.py
Mechanical application of black. 
Meaningful changes are primarily in test files to remove assertions on `get_pixels` dataframe and replaces with checks against `get_healpix_pixels() -> List[HealpixPixel]`.
=> Run black formatting and remove `get_pixels`

benchmarks/benchmarks.py, pyproject.toml, src/lsdb/core/crossmatch/kdtree_gnomonic_match.py, src/lsdb/core/crossmatch/kdtree_match.py, tests/lsdb/catalog/test_crossmatch.py
This implements #41, replacing the current kD-tree cross-matching algorithm `KdTreeCrossmatch` with an updated version using the Cartesian coordinates of the objects on the unit sphere instead of gnomonic projection. The gnomonic projection implementation is currently moved into new `KdTreeGnomonicCrossmatch` (few bugs fixed), but I plan to remove it in another PR.
The new implementation should be more accurate for the edge-cases, because 1) looking for neighbors in the Cartesian space is equivalent to spherical matches, 2) current implementation looking for neighbors in gnomonic projection coordinate space. I believe that the proposed method is equivalent to [one used by `astropy`](https://github.com/astropy/astropy/blob/7a502230364e57c98e6a5f0184d9afb8831e7dc4/astropy/coordinates/matchin …
=> 3dtree cross-matching

src/lsdb/catalog/catalog.py, tests/lsdb/catalog/test_catalog.py
Creates wrappers for the `query` and `assign` operations on a catalog's data frame. Closes #45.
=> Wrappers for Dataframe query and assign operations

src/lsdb/io/to_hipscat.py
Changes the `write_partitions` method to use dask_delayed to write out partitions in parallel in the dask task graph. This is [how dask writes to disk](https://github.com/dask/dask/blob/b2f11d026d2c6f806036c050ff5dbd59d6ceb6ec/dask/dataframe/io/csv.py#L799).
=> Parallelize `to_hipscat` using dask delayed

src/lsdb/dask/crossmatch_catalog_data.py
Replaces distance column name hard coded into crossmatch algorithm dask meta with a constant.
=> Replace string with constant

src/lsdb/catalog/catalog.py, src/lsdb/dask/crossmatch_catalog_data.py, src/lsdb/dask/join_catalog_data.py, tests/conftest.py, tests/lsdb/catalog/test_join.py
Adds the `join` method to the catalog class, performing a spatial join that merges tables based on a shared column between catalogs.
=> Add Catalog Joining on a column

src/lsdb/loaders/hipscat/hipscat_catalog_loader.py, src/lsdb/loaders/hipscat/hipscat_loading_config.py, src/lsdb/loaders/hipscat/read_hipscat.py, tests/lsdb/loaders/hipscat/test_read_hipscat.py
Adds kwargs to `read_hipscat` and tests the loading of a HiPSCat catalog using a subset of columns. Closes #78.
=> Add kwargs to read_hipscat to filter columns

src/lsdb/loaders/dataframe/dataframe_catalog_loader.py
It fixes the access to the "ra" and "dec" column values when computing the `hipscat_id` in `from_dataframe()`.
=> Fix access to "ra" and "dec" values in `from_dataframe`

README.md
The link to the logo in the readme.md file was broken. It was pointing to the LSST Corporation website, and the website got a complete remodel when moving to Discovery Alliance. The link is now pointing to the image hosted with repo of TAPE project.
=> Update README.md - fix link to the LINCC logo

src/lsdb/catalog/catalog.py, src/lsdb/io/to_hipscat.py, tests/lsdb/catalog/test_catalog.py
Allows `to_hipscat` to overwrite existing catalogs. Closes #94.
=> Allow `to_hipscat` to overwrite catalogs

.pre-commit-config.yaml, docs/requirements.txt, pyproject.toml
This is related to #121 , but doesn't really close it.
- we're using `dask[distributed]` and `dask[dataframe]`, so let's explicitly depend on them.
- remove extra spherical geometry dep on docs
- maybe fix github being sad in `pyproject.toml` about `project.urls`?
=> Clean up some dependencies

src/lsdb/core/search/polygon_search.py, tests/lsdb/catalog/test_polygon_search.py
Validates polygons used for catalog search. They must contain at least three vertices (without duplicates) and form a non-degenerate region (i.e., the vertices cannot be on a single great circle). Closes #120.
=> Add more thorough polygon validation

pyproject.toml
Adds dependency on `dask[complete]` which includes Dask diagnostics to spin up the profiling dashboard. Closes #121.
=> Specify dependency on `dask[complete]`

src/lsdb/dask/crossmatch_catalog_data.py, src/lsdb/dask/join_catalog_data.py, src/lsdb/dask/merge_catalog_functions.py, src/lsdb/loaders/hipscat/margin_catalog_loader.py
The crossmatch and join methods all do pretty similar things, in that they align the left and right catalog partitions, then apply a function to the matching pairs of partitions. 
This PR refactors their methods to use a more general helper function `align_and_apply` that can perform this alignment and applying a function over them while allowing for differences like the association catalog needing to also be aligned for joining. This should also make it easier to add margins to each of these methods.
=> Refactor join and crossmatch partition alignment and applying code

docs/index.rst, docs/notebooks.rst, docs/notebooks/ztf_bts-ngc.ipynb
This is a simple toy-example of LSDB usage without pre-HiPSCated data. It takes few seconds to run, because each time it runs it downloads some data from both ZTF and Vizier.
It also adds a new dev dependency, astriquery. We need it to download NGC via Vizier.
=> Documentation notebook with ZTF BTS vs NGC cross-match example

src/lsdb/core/search/cone_search.py, src/lsdb/core/search/polygon_search.py
Filters partitions with a numpy array mask instead of appending a new dataframe column and applying filtering based on it (for both `cone` and `polygon` search). This clears performance warnings of this kind: `PerformanceWarning: DataFrame is highly fragmented`. Closes #102.
=> Remove performance warnings on filtering

src/lsdb/catalog/catalog.py, tests/lsdb/catalog/test_catalog.py
Adds a simple `head` method to the catalog to get a few rows of data for previewing purposes. Closes #106.
=> Add `head` method to catalog

src/lsdb/dask/merge_catalog_functions.py, tests/lsdb/catalog/test_join.py
Forces the `_hipscat_index` type on joined catalogs to be `uint64`. We were not enforcing the index type before so Pandas was infering `int64`, which is incorrect. Closes #145.
=> Fix inconsistent `_hipscat_index` type

src/lsdb/__init__.py, tests/lsdb/test_packaging.py
Adds the `__version__` property to show the installed package version (similar to what TAPE did in https://github.com/lincc-frameworks/tape/pull/302). Closes #160.
=> Add package version property

src/lsdb/core/search/box_search.py
1. Default `mask` array had wrong dtype - it would cause a dataframe where all the elements are the second row of the original data frame
2. Use `np.asarray` to prevent data copy
=> Numpy tricks for box_search.py

src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/catalog/margin_catalog.py, tests/lsdb/catalog/test_box_search.py, tests/lsdb/catalog/test_cone_search.py, tests/lsdb/catalog/test_polygon_search.py
Adds the `_search` method to the margin catalog, refactoring some common logic to the `HealpixDataset` class while adding the margin specific logic to add the neighboring pixels when performing the search. The `_search` method in the Catalog class now also calls the same search on the margin catalog and includes that in the result if it exists.
=> Add spatial filtering to margin catalogs

benchmarks/benchmarks.py, src/lsdb/loaders/dataframe/from_dataframe.py, tests/lsdb/loaders/dataframe/test_from_dataframe.py
Unit tests have slowed considerably with the addition of #175. This change enables a non-default option to suppress generating a margin cache when creating a new catalog via `from_dataframe`. 
In particular, the `test_catalog_pixels_nested_ordering` test is creating a margin cache for the `small_sky_source` catalog, but the margin cache is never referenced, and only the behavior of the primary catalog is under test in this method.
Times for local pytest runs as of main:
```
$ pytest
39.53s 
43.78s
$ pytest --durations=10
27.63s call     tests/lsdb/loaders/dataframe/test_from_dataframe.py::test_catalog_pixels_nested_ordering
2.76s call     tests/lsdb/loaders/dataframe/test_from_dataframe.py::test_from_dataframe_sky_source_with_margins
2.12s call …
```
=> Optionally suppress margin on from_dataframe

src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/io/to_hipscat.py, tests/lsdb/catalog/test_margin_catalog.py
Refactors the `to_hipscat` method to enable saving a margin catalog to disk. Closes #206.
=> Save margin catalog to disk

src/lsdb/loaders/hipscat/abstract_catalog_loader.py
uses `_common_metadata` instead of `_metadata`, which gives a large performance improvement to loading catalogs
=> Change metadata loading method to use right file

docs/notebooks/import_catalogs.ipynb, src/lsdb/catalog/dataset/dataset.py, tests/lsdb/catalog/test_catalog.py
Closes #126 
- includes the name of the catalog
- doesn't issue a warning from within dask
=> Use custom representation for catalog.

src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_catalog.py
Updates default value of skymap non covered tiles from 0 to healpy's `UNSEEN` constant. Closes #248.
=> Update Skymap default

docs/gettingstarted/quickstart.ipynb
Adds the quickstart guide which exemplifies the usage of:
- `from_dataframe`, to create an object catalog with a handful of points
- `read_hipscat`, to Ioad a catalog in HiPSCat format
- `crossmatch`, to perform a K nearest neighbors crossmatch between two catalogs
- `to_hipscat`, to save the resulting catalog to disk
Closes #224.
=> Add quickstart guide

.github/workflows/smoke-test.yml, .github/workflows/testing-and-coverage.yml
Smoke tests are failing with silly errors that seem related to recent regressions in dask with python 3.11.8->3.11.9.
https://github.com/dask/dask/issues/11038
=> Pin python 3.11 version in CI.

.gitattributes, .github/workflows/pre-commit-ci.yml, .github/workflows/smoke-test.yml, README.md, docs/gettingstarted/contributing.rst, docs/index.rst
Change links to other LINCC-related readthedocs pages to use `en/stable` instead of `en/latest`.
See https://github.com/astronomy-commons/lsdb/issues/260
=> Change readthedocs URLs to stable

docs/conf.py
Add cross-references to the hipscat library in the API documentation. Closes #155.
=> Cross-reference hipscat in the API docs

src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_catalog.py
Allows accessing catalog through square brackets by overloading `__getitem__` to pass through to the Dask DataFrame and covert result to catalog if necessary.
Closes #251
=> Add __getitem__ accessor for catalogs

pyproject.toml, src/lsdb/catalog/dataset/dataset.py, src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/dask/crossmatch_catalog_data.py, src/lsdb/dask/join_catalog_data.py, src/lsdb/dask/merge_catalog_functions.py, src/lsdb/loaders/dataframe/from_dataframe_utils.py, src/lsdb/loaders/dataframe/margin_catalog_generator.py, src/lsdb/loaders/hipscat/association_catalog_loader.py, tests/conftest.py, tests/lsdb/catalog/test_association_catalog.py
Dask updating to use dask expressions for dataframes introduced a few behavior changes that caused errors. This is mostly Sandro's work to fix the bugs introduced. I think there should probably be some more refactoring, but I wanted to get this in with it causing issues with Tape integration and with python 3.11.9+ as per #285.
- Empty DataFrames are now handled differently, with `from_delayed` now failing for an empty list of delayed objects, and `from_pandas` with `npartitions=0` generating a DataFrame that gives an error on `compute()`. For now, the solution is to make a ddf with a single empty pandas df as a partition.  I thought that we were generating empty data frames properly before, but this is actually what Dask used to do with the empty input cases, it just throws an error now …
=> Add support for Dask versions >=2024.3.0 with dask expressions

src/lsdb/loaders/hipscat/abstract_catalog_loader.py
Changes the abstract catalog loader to use the new hipscat method to get multiple paths introduced in astronomy-commons/hipscat#258
=> Use faster hipscat paths method

src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_catalog.py
Adds the `map_partitions` function to the catalog, wrapping the dask `map_partitions` call. Also includes the option to call the ufunc with the partition's HealpixPixel, and to work out the output meta by calling with an empty partition. Closes #283
=> Add map_partitions function to catalog

.github/workflows/smoke-test.yml, .github/workflows/testing-and-coverage.yml, pyproject.toml, src/lsdb/__init__.py
- Sets dask config to not use dask expressions in the __init__ when importing lsdb by setting the `dataframe.query-planning` config setting to False. 
- Removes dask requirement version pin in pyproject and python 3.11 version pin in workflows.
=> Support dask versions >=2024.3 by disabling dask expressions

src/lsdb/__init__.py, src/lsdb/catalog/association_catalog.py, src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/catalog/margin_catalog.py, src/lsdb/dask/merge_catalog_functions.py, src/lsdb/loaders/dataframe/dataframe_catalog_loader.py, src/lsdb/loaders/dataframe/from_dataframe_utils.py, src/lsdb/loaders/dataframe/margin_catalog_generator.py, src/lsdb/loaders/hipscat/abstract_catalog_loader.py, src/lsdb/loaders/hipscat/association_catalog_loader.py, tests/lsdb/catalog/test_catalog.py, tests/lsdb/catalog/test_merge.py
Changes dask data frame methods to use the legacy ones directly without needing to set the dask config to disable query planning.
=> Update dask dataframe imports to use legacy dataframe directly

src/lsdb/catalog/margin_catalog.py, src/lsdb/core/search/box_search.py, src/lsdb/core/search/cone_search.py, src/lsdb/core/search/polygon_search.py
Removes the usage of the `PixelTreeBuilder` class which was deleted from hipscat in https://github.com/astronomy-commons/hipscat/pull/266.
=> Remove usage of pixel tree builder

benchmarks/benchmarks.py, src/lsdb/core/crossmatch/bounded_kdtree_match.py, src/lsdb/core/crossmatch/kdtree_match.py, src/lsdb/dask/crossmatch_catalog_data.py, src/lsdb/dask/join_catalog_data.py, tests/lsdb/catalog/test_crossmatch.py, tests/lsdb/core/test_kdtree_validation.py
Changes the crossmatch `require_right_margin` argument to be False, by default. It also updates the warning messages issued when the right catalog does not have a margin. Closes #296 and #297.
=> Change `require_right_margin` default and update warning message

src/lsdb/dask/crossmatch_catalog_data.py, tests/lsdb/catalog/test_crossmatch.py
Fixes the crossmatch routine, which failed whenever there was an empty left partition. Closes #310.
=> Allow empty left partitions on crossmatch

src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/core/crossmatch/abstract_crossmatch_algorithm.py, src/lsdb/core/crossmatch/kdtree_match.py, src/lsdb/core/search/abstract_search.py, src/lsdb/core/search/box_search.py, src/lsdb/core/search/cone_search.py, src/lsdb/core/search/polygon_search.py, src/lsdb/dask/crossmatch_catalog_data.py, src/lsdb/dask/join_catalog_data.py, src/lsdb/dask/merge_catalog_functions.py, tests/lsdb/core/test_kdtree_validation.py
Changes the crossmatch, join, and search delayed calls to only pass the hipscat `catalog_info` instead of the full `Catalog` object. Avoids pickling and sending excess data to dask workers, and fixes #316 issues pickling MOCpy objects.
=> Only pass catalog_info to delayed tasks instead of full hipscat catalog metadata

benchmarks/benchmarks.py, src/.pylintrc, src/lsdb/dask/crossmatch_catalog_data.py, src/lsdb/dask/merge_catalog_functions.py, src/lsdb/loaders/dataframe/dataframe_catalog_loader.py, src/lsdb/loaders/dataframe/from_dataframe.py, tests/.pylintrc, tests/lsdb/catalog/test_crossmatch.py, tests/lsdb/loaders/dataframe/test_from_dataframe.py
Uses the MOC alignment functions recently added to hipscat to perform alignment for crossmatch and join with higher order coverage. Generates a MOC when `from_dataframe` is called.
=> Use MOCs for alignment and generate MOC in from_dataframe

.pre-commit-config.yaml, src/lsdb/__init__.py, src/lsdb/loaders/hipscat/abstract_catalog_loader.py, src/lsdb/loaders/hipscat/hipscat_catalog_loader.py, src/lsdb/loaders/hipscat/hipscat_loading_config.py, src/lsdb/loaders/hipscat/read_hipscat.py, src/lsdb/loaders/hipscat/read_hipscat.pyi, tests/lsdb/loaders/hipscat/test_read_hipscat.py
Adds a `margin_path` argument to the `read_hipscat` interface allowing for standard HiPSCat catalogs to be loaded with margins (in parquet format) from their path on disk. Closes #314.
=> Allow margin path argument in `read_hipscat`

src/lsdb/catalog/catalog.py, src/lsdb/catalog/margin_catalog.py, src/lsdb/core/search/abstract_search.py, src/lsdb/core/search/box_search.py, src/lsdb/core/search/cone_search.py, src/lsdb/core/search/index_search.py, src/lsdb/core/search/order_search.py, src/lsdb/core/search/pixel_search.py, src/lsdb/core/search/polygon_search.py, src/lsdb/dask/merge_catalog_functions.py, src/lsdb/loaders/hipscat/abstract_catalog_loader.py, src/lsdb/loaders/hipscat/hipscat_catalog_loader.py, src/lsdb/loaders/hipscat/margin_catalog_loader.py, tests/lsdb/catalog/test_crossmatch.py, tests/lsdb/loaders/hipscat/test_read_hipscat.py
Refactors Search Filter class to use hipscat MOC filtering methods. MOCs are now filtered and passed through to the returned catalog after filtering, and filtering now doesn't need to generate and align multiple pixel trees, and reuses more code from hispcat and has less code overall.
Margin filtering now uses Margin Filter code in hipscat, so performing a search filter in read_hipscat on a margin catalog now works.
Fixes #330, fixes #329, fixes #268
=> Use MOCs for spatial filters

src/lsdb/loaders/hipscat/hipscat_loading_config.py, src/lsdb/loaders/hipscat/read_hipscat.py, src/lsdb/loaders/hipscat/read_hipscat.pyi, tests/lsdb/loaders/hipscat/test_read_hipscat.py
Removes the overly strict check on the margin cache argument to allow the use of path-like objects. Closes #343.
=> Allow path-like objects in the margin cache argument

docs/tutorials/import_catalogs.ipynb, src/lsdb/loaders/dataframe/dataframe_catalog_loader.py, src/lsdb/loaders/dataframe/from_dataframe.py, tests/lsdb/catalog/test_crossmatch.py, tests/lsdb/loaders/dataframe/test_from_dataframe.py
Provides a better threshold estimation in `from_dataframe` for when no partition size or threshold are provided, attempting to create partitions that in memory will be of roughly 1Gib. 
It also increases the lowest and highest order defaults to 3 and 7, respectively. Closes #213.
=> Update catalog threshold estimation

src/lsdb/io/to_hipscat.py, src/lsdb/loaders/hipscat/abstract_catalog_loader.py
See cloudtests smoke failure when using `storage_options`: https://github.com/astronomy-commons/hipscat-cloudtests/actions/runs/9495013490
=> Specify argument name for optional storage_options argument.

.gitignore, src/lsdb/loaders/hipscat/abstract_catalog_loader.py, src/lsdb/loaders/hipscat/hipscat_loading_config.py
This PR works on top of `hipscat` [#291 PR](https://github.com/astronomy-commons/hipscat/pull/291).
It creates the url params dict to be transformed to url params in hipscat.
=> Support to query params on http filesystem

src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_catalog.py
Currently if the user returns a non data frame when calling map_partitions (e.g. returning a series) it uses this as the ddf in another catalog, which causes errors when the catalog expects a ddf but actually gets a series.
This updates the map_partitions method to check that the return type is a data frame. If the return type isn't, the raw dask collection is returned instead of creating the catalog.
Fixes #324
=> Support map_partitions ufunc with non data frame output

docs/tutorials/import_catalogs.ipynb, docs/tutorials/margins.ipynb, docs/tutorials/quickstart.ipynb, docs/tutorials/working_with_large_catalogs.ipynb
Related to https://github.com/astronomy-commons/lsdb/issues/376
- use data.lsdb.io instead of epyc, where possible.
- expand on reasons for using from_dataframe vs hipscat-import, and provide link to that package's RTD
- don't do extra install of aiohttp (see https://github.com/astronomy-commons/hipscat/pull/291)
nb: we're not ready to take the `lowest_healpix_order` references out of the "import catalogs" notebook yet, as the two modes have different defaults and won't result in the same catalog. see https://github.com/astronomy-commons/lsdb/issues/377
=> Docs hot fixes

src/lsdb/loaders/dataframe/dataframe_catalog_loader.py, src/lsdb/loaders/dataframe/from_dataframe.py, tests/lsdb/loaders/dataframe/test_from_dataframe.py
Closes #377 
- Uses the same default values for orders and thresholds as the import pipeline
- Adds new `drop-empty-siblings` argument
- Uses the same partition calculation mechanism as hipscat-import (`generate_alignment` vs `compute_pixel_map`). This enabled a simplification of the pixel mapping logic.
- Gives a warning when the input dataframe is too large (see #376)
- Adds several missing params to docstrings.
=> Make from_dataframe defaults consistent with hipscat-import

src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/core/plotting/skymap.py, src/lsdb/core/search/polygon_search.py, src/lsdb/dask/merge_catalog_functions.py, src/lsdb/loaders/dataframe/margin_catalog_generator.py, tests/lsdb/catalog/test_catalog.py, tests/lsdb/loaders/dataframe/test_from_dataframe.py
Uses hipscat's wrapper around healpy functions, to hopefully ease the migration off healpy.
Related to: https://github.com/astronomy-commons/hipscat/issues/53
=> Use healpix shim for healpy operations.

src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/healpix_dataset.py, tests/conftest.py, tests/lsdb/catalog/test_nested.py
Part of #372, wraps the dropna function from nested_dask as a catalog method
=> Wrap nested_dask dropna function

src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/dask/merge_catalog_functions.py, tests/lsdb/catalog/test_nested.py, tests/lsdb/catalog/test_polygon_search.py
Adds the `reduce` function to the `Catalog` class, wrapping the `reduce` function in `nd.NestedFrame`
Fixes #420
=> Wrap nested_dask `reduce`

src/lsdb/loaders/dataframe/dataframe_catalog_loader.py, src/lsdb/loaders/dataframe/from_dataframe.py, src/lsdb/loaders/dataframe/margin_catalog_generator.py, tests/lsdb/catalog/test_polygon_search.py
Explode kwargs in `from_dataframe` to improve visibility of the ra and dec column arguments. Also add a conditional test skip when checking for invalid polygon shapes because of a HEALPy bus error on macOS. Closes #432.
=> Explode kwargs for ra and dec in `from_dataframe`

docs/requirements.txt, src/lsdb/catalog/catalog.py, tests/lsdb/catalog/test_crossmatch.py, tests/lsdb/catalog/test_join.py
Uses the `PixelAlignment` object's moc as the moc in the output catalogs of join and crossmatch operations.
Fixes #428
=> Use Alignment moc in crossmatch/join operations

src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_catalog.py, tests/lsdb/catalog/test_nested.py
Fix the catalog structure, which was being shallow copied, for operations such as `query`, `dropna` and `nest_lists`. It adds a method that performs the deep copy of the underlying structure and that allows to override catalog info parameters (e.g. we invalidate rows setting `total_rows` to 0). It further adds a missing docstring to `reduce`.
=> Fix shallow copy of catalog structure

src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/io/to_hats.py, tests/lsdb/catalog/test_catalog.py
Generate the sky map histogram at a high order when writing catalogs to disk. Closes #359.
=> Write point map on `to_hipscat`

src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_catalog.py
Updates plotting calls to use plotting functions introduced with astronomy-commons/hats#374
=> Use new healpix plotting from hats

src/lsdb/loaders/hats/hats_loading_config.py, src/lsdb/loaders/hats/read_hats.py, src/lsdb/loaders/hats/read_hats.pyi, tests/conftest.py, tests/lsdb/catalog/test_crossmatch.py, tests/lsdb/loaders/hats/test_read_hats.py
Remove code path that allows to provide a margin object to `read_hats`. Adds a simple validation to make sure that the loaded margin has a compatible schema. Closes #473.
=> Remove margin object from `read_hats`

docs/tutorials.rst, docs/tutorials/manual_verification.ipynb, docs/tutorials/remote_data.ipynb
Closes #392.
Partially resolves #386 (documents the `Catalog.schema` attribute).
=> Add catalog validation tutorial

src/lsdb/io/to_hats.py, src/lsdb/loaders/dataframe/dataframe_catalog_loader.py
Closes #478 
I was looking into something unrelated, and observed this and got annoyed.
=> Address warning on writing catalog.

docs/tutorials.rst, docs/tutorials/join_catalogs.ipynb
Add a notebook to demonstrate joining Gaia DR3 with Gaia EDR3 distances. Closes #388.
=> Add join catalogs notebook

pyproject.toml, tests/lsdb/catalog/test_catalog.py
Currently we have a single test failure when querying with column names that include a space. Here is the corresponding Nested-Pandas issue: https://github.com/lincc-frameworks/nested-pandas/issues/174
=> Update nested-dask to v0.3.0

docs/tutorials/join_catalogs.ipynb, docs/tutorials/margins.ipynb, src/lsdb/__init__.py
It allows to do `from lsdb import ConeSearch`
=> Reimport `*Search` from root `__init__.py`

tests/lsdb/catalog/test_catalog.py
lincc-frameworks/nested-pandas#174 has been closed.
Columns names which contain spaces and other special characters are now supported (even if they'd be weird).
=> Test can be unskipped for column names with spaces

src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/catalog/margin_catalog.py, src/lsdb/core/search/moc_search.py, tests/lsdb/catalog/test_moc_search.py
Adds the `MOCSearch` class, and the `search_moc` method to the catalog that allows filtering a catalog by a mocpy object.
Also adds a default `search` implementation to the `HealpixDataset` class. Previously searching was only possible on the catalog subclass.
=> Add MOC Filter

src/lsdb/dask/merge_catalog_functions.py, src/lsdb/loaders/dataframe/from_dataframe.py, src/lsdb/loaders/dataframe/margin_catalog_generator.py, tests/lsdb/catalog/test_catalog.py, tests/lsdb/loaders/dataframe/test_from_dataframe.py
Updates `nside2***` and `ang2pix`
=> Update to hats healpix math

.github/workflows/smoke-test.yml, .github/workflows/testing-and-coverage.yml, .github/workflows/testing-windows.yml, .setup_dev.sh, docs/requirements.txt, pyproject.toml, src/lsdb/core/search/polygon_search.py, tests/conftest.py, tests/lsdb/catalog/test_catalog.py, tests/lsdb/catalog/test_polygon_search.py, tests/lsdb/loaders/hats/test_read_hats.py
Now that we don't depend on healpy, everything should run well on Windows. This adds a test to confirm that.
`lsst-sphgeom` is not available for windows, so this makes it an optional dependency, conditionally disabling tests that require it.
See: https://github.com/astronomy-commons/hats/pull/440
=> Test on Windows OS.

.copier-answers.yml, .github/workflows/asv-main.yml, .github/workflows/asv-nightly.yml, .github/workflows/asv-pr.yml, .github/workflows/build-documentation.yml, .github/workflows/pre-commit-ci.yml, .github/workflows/publish-to-pypi.yml, .github/workflows/smoke-test.yml, .github/workflows/testing-and-coverage.yml, .pre-commit-config.yaml, .readthedocs.yml, benchmarks/asv.conf.json, pyproject.toml, src/.pylintrc, tests/.pylintrc
Support dropped in hats. See https://github.com/astronomy-commons/hats/pull/442
=> Drop support for python 3.9

src/lsdb/core/search/abstract_search.py, src/lsdb/core/search/cone_search.py, tests/lsdb/catalog/test_cone_search.py
Adds the plot method to the abstract spatial filters. Implements it for cone search.
=> Add plotting to search filters

docs/contact.rst, docs/developer/contributing.rst
- Adds communication options, and embeds the HATS/LSDB calendar.
- Removes some duplicate/outdated installation instructions
- Points to LF code of conduct
=> Spruce up the contribution guide.

src/lsdb/dask/merge_catalog_functions.py, tests/lsdb/catalog/test_crossmatch.py
=> Add more helpful error with non overlapping catalogs

docs/requirements.txt, src/lsdb/loaders/dataframe/dataframe_catalog_loader.py, src/lsdb/loaders/dataframe/from_dataframe_utils.py, tests/lsdb/loaders/dataframe/test_from_dataframe.py
Save named indices when importing data with `from_dataframe`. When named indices appear in data they are usually relevant and should not be dropped, at the risk of rendering the catalog useless (e.g. if they are object/source IDs).
=> Save named indices in `from_dataframe`

src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/dataset.py, src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/core/crossmatch/abstract_crossmatch_algorithm.py, src/lsdb/core/crossmatch/bounded_kdtree_match.py, src/lsdb/core/crossmatch/kdtree_match.py, src/lsdb/core/crossmatch/kdtree_utils.py, src/lsdb/core/plotting/plot_points.py, src/lsdb/core/plotting/skymap.py, src/lsdb/core/search/abstract_search.py, src/lsdb/core/search/pixel_search.py, src/lsdb/dask/crossmatch_catalog_data.py, src/lsdb/dask/divisions.py, src/lsdb/dask/join_catalog_data.py, src/lsdb/dask/merge_catalog_functions.py, src/lsdb/dask/merge_map_catalog_data.py, src/lsdb/dask/partition_indexer.py, src/lsdb/loaders/dataframe/dataframe_catalog_loader.py, src/lsdb/loaders/dataframe/from_dataframe_utils.py, src/lsdb/loaders/dataframe/margin_catalog_generator.py, src/lsdb/loaders/hats/hats_loading_config.py, src/lsdb/loaders/hats/read_hats.py, src/lsdb/loaders/hats/read_hats.pyi, src/lsdb/types.py
See also: https://github.com/astronomy-commons/hats/pull/441
A few kinds of typing imports remain, but the most annoying/silly ones have been removed.
=> Remove typing imports for List, Tuple, Union

src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_catalog.py
Add the missing args and kwargs for the user-defined function when deriving the meta for `map_partitions`. Closes #564.
=> Pass args and kwargs to derive meta on `map_partitions`

docs/index.rst
We don't use big-O with numbers
https://en.wikipedia.org/wiki/Big_O_notation
=> O(1B) -> ~10⁹

src/lsdb/loaders/hats/read_hats.py, tests/lsdb/loaders/hats/test_read_hats.py
Passing "all" as the argument to the "read_hats" keyword now loads all columns, ignoring the default columns property.
Fixes #563
=> Add "all" options to read_hats columns

docs/advanced-topics.rst, docs/index.rst, docs/science-notebooks.rst, docs/tutorials.rst
Tutorials currently has a large number of pages within it, which makes it hard to navigate. This splits the sections into Tutorials, Advanced topics, and Example Science Notebooks.
=> Separate tutorials into multiple sections

docs/contact.rst
Changes LSSTC to LSST Discovery Alliance in our contact section of the Documentation.
=> LSSTC to LSST Discovery Alliance

src/lsdb/catalog/association_catalog.py, src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/core/search/abstract_search.py, src/lsdb/dask/merge_catalog_functions.py, src/lsdb/io/schema.py, src/lsdb/io/to_hats.py, src/lsdb/loaders/dataframe/margin_catalog_generator.py, src/lsdb/loaders/hats/read_hats.py, tests/conftest.py, tests/lsdb/catalog/test_box_search.py, tests/lsdb/catalog/test_catalog.py, tests/lsdb/catalog/test_cone_search.py, tests/lsdb/catalog/test_crossmatch.py, tests/lsdb/catalog/test_index_search.py, tests/lsdb/catalog/test_join.py, tests/lsdb/catalog/test_order_search.py, tests/lsdb/catalog/test_polygon_search.py, tests/lsdb/loaders/dataframe/test_from_dataframe.py, tests/lsdb/loaders/hats/test_read_hats.py
Refactors catalogs to create returned objects using a new `_create_updated_dataset` that sets `total_rows` to 0 and updates the `schema` and `default_columns` properties in the `hc_structure`. 
Fixes #566 fixes #178 fixes #143
=> Operations update metadata correctly

requirements.txt, tests/lsdb/catalog/test_catalog.py, tests/lsdb/loaders/hats/test_read_hats.py
Add two unit tests that verify that we only initialize `UPath` once per catalog, and that we do not hit `hats.io.file_io.file_pointer.get_upath_for_protocol` repeatedly because it can be expensive. 
Related to https://github.com/astronomy-commons/hats/pull/466.
=> Verify `UPath` initialization

src/lsdb/catalog/catalog.py, src/lsdb/loaders/dataframe/from_dataframe.py, tests/lsdb/catalog/test_crossmatch.py
Closes #578 
Note:
- The function signatures between `crossmatch` and `crossmatch_dataframe` were almost completely preserved, except the omission of `require_right_margin`, which doesn't make sense for a dataframe where we can (and unless otherwise specified in kwargs, will) generate the margin on the spot.
- I took my best shot at allowing the user to pass kwargs to `from_dataframe`, but I'm not thrilled at the need to keep this list up to date with the possible args `from_dataframe` will accept. However, without filtering the overall kwargs at this point, `self.crossmatch` on L312 will crash when encountering unexpected kwargs. Open to alternate strategies here.
=> Crossmatch pandas dataframe with an lsdb catalog

tests/lsdb/catalog/test_catalog.py, tests/lsdb/catalog/test_cone_search.py, tests/lsdb/catalog/test_crossmatch.py, tests/lsdb/catalog/test_join.py
Serves to test upstream changes in https://github.com/astronomy-commons/hats/pull/470
=> Add testing after updating catalog structure.

.github/ISSUE_TEMPLATE/4-release_tracker.md
Breaks out the conda-forge release flow into separate section, since the github/pypi stuff takes way less time, and makes it clearer when we're just waiting on conda-forge releases.
And add reminders to pin versions for pyproject.toml, not just conda recipe.
=> Re-arrange to match actual release flow.

src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_catalog.py
Add a few more preview methods to `lsdb.Catalog`, allowing a user to get a quick sense of what data is in the catalog.  New methods are:
```python
def tail(self, n: int = 5) -> npd.NestedFrame:
"""Returns a few rows of data from the end of the catalog for previewing purposes.
"""
def sample(self, partition_id: int, n: int = 5) -> npd.NestedFrame:
"""Returns a few randomly sampled rows from a given partition.
"""
def random_sample(self, n: int = 5) -> npd.NestedFrame:
"""Returns a few randomly sampled rows, like self.sample(),
except that it randomly samples all partitions in order to
fulfill the rows.
"""
```
Closes #549.
=> New catalog preview methods tail, sample, and random_sample

src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_catalog.py
When an LSDB catalog is displayed in a Jupyter notebook, the number of partitions in a catalog `c` is available as `n = len(c.get_healpix_pixels())`. But the information is displayed as `npartitions=<n>` in the notebook, leading the user to expect a property with the name `npartitions`.
Closes #627 .
=> Add npartitions property to top of catalog.

tests/lsdb/catalog/test_catalog.py
The new `.random_sample` method on `Catalog` had a couple of cases not covered by unit testing. This PR covers those cases (no samples returned, sampling from filtered catalog).
=> Improve code coverage of `.random_sample`

src/lsdb/catalog/dataset/dataset.py, src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_catalog.py, tests/lsdb/loaders/hats/test_read_hats.py
Adds the properties `all_columns` and `original_schema` to the dataset class. Fixes #654
=> Add all columns and original schema properties

src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/nested/core.py, tests/lsdb/catalog/test_nested.py
Closes #624. Additionally adds some documentation for a slight change in reduces args/kwargs behavior introduced in nested-pandas v0.4.0+
=> Reduce Updates: infer_nesting and docs for reduce arg limits

src/lsdb/catalog/catalog.py, tests/lsdb/catalog/test_catalog.py
Add descriptive messages to Catalog's `.iloc` and `.loc` accessors. The message for `.loc` directs users to the newly created `id_search` and shortly describes how to call it. Closes #667 and closes #668.
=> Add .loc/.iloc accessors

.pre-commit-config.yaml, src/lsdb/catalog/dataset/dataset.py, tests/lsdb/catalog/test_catalog.py
Building on the `all_columns` property and the default-columns behavior, display to the user in Jupyter notebooks when a catalog is lazily loaded, how many columns have been loaded versus how many are available.
Closes #662 .
=> Display the total number of available columns

src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_nested.py
Fixes #583 
Modifies the lsdb wrappers around `NestedFrame.from_lists` so they match the nested-pandas behavior of allowing the `base_columns` to be optional. When`base_columns` are not provided, all non-list columns are inferred to be based columns. This required no changes from LSDB outside of the function signatures of the wrappers.
=> Support only providing list_columns in catalog.nest_lists

.pre-commit-config.yaml, src/lsdb/catalog/catalog.py, src/lsdb/catalog/dataset/dataset.py, src/lsdb/catalog/dataset/healpix_dataset.py, tests/lsdb/catalog/test_catalog.py
Now that we have default columns for catalogs, there are usually columns available on disk that aren't pulled into memory, and this is even more true when the `columns=` argument is used.  When the user tries to reference columns that are part of the catalog but which weren't loaded, the error messages imply that the columns were never available.  Instead, building on the `all_columns` property, give a more specific error when the user tries to access an unloaded column.
Closes #685 and #765 .
=> Raise a helpful error message when the user is accessing a catalog's column that hasn't been loaded.

tests/lsdb/catalog/test_catalog.py, tests/lsdb/io/test_to_hats.py
`to_hats` is implemented under `lsdb/io/`, so it's reasonable that the tests would go there as well. The `test_catalog.py` file is very long and hard to find the tests you want, so splitting them into files by theme / catalog method is still reasonable.
=> Split to_hats tests to separate file.

.pre-commit-config.yaml, benchmarks/benchmarks.py, docs/tutorials/catalog_object.ipynb, docs/tutorials/filtering_large_catalogs.ipynb, docs/tutorials/getting_data.ipynb, docs/tutorials/import_catalogs.ipynb, docs/tutorials/margins.ipynb, docs/tutorials/pre_executed/des-gaia.ipynb, docs/tutorials/pre_executed/index_table.ipynb, docs/tutorials/pre_executed/join_catalogs.ipynb, docs/tutorials/pre_executed/manual_verification.ipynb, docs/tutorials/pre_executed/map_partitions.ipynb, docs/tutorials/pre_executed/plotting.ipynb, docs/tutorials/region_selection.ipynb, docs/tutorials/remote_data.ipynb, docs/tutorials/row_filtering.ipynb, src/lsdb/__init__.py, src/lsdb/loaders/__init__.py, src/lsdb/loaders/hats/__init__.py, src/lsdb/loaders/hats/read_hats.py, tests/conftest.py, tests/data/generate_data.ipynb, tests/lsdb/catalog/test_association_catalog.py, tests/lsdb/catalog/test_catalog.py, tests/lsdb/catalog/test_crossmatch.py, tests/lsdb/catalog/test_index_search.py, tests/lsdb/catalog/test_join.py, tests/lsdb/catalog/test_margin_catalog.py, tests/lsdb/catalog/test_nested.py, tests/lsdb/loaders/hats/test_read_hats.py
`lsdb.read_hats` remains a thin wrapper to `lsdb.hats_catalog`, with its own docstring indicating that it is one (rather than a direct alias).
This PR is in two commits, one which makes the small and simple rename, and the second, which renames all the `.read_hats` calls and references within the project.
Closes #464 .
=> Rename lsdb.read_hats to lsdb.hats_catalog

src/lsdb/__init__.py
In implementing the notebook for #733, I wanted to just do `import lsdb` and get all of the other things imported from that top-level namespace. Those are the most critical functions, after all!
=> Add more imports to top-level init.

docs/tutorials/pre_executed/map_partitions.ipynb, docs/tutorials/row_filtering.ipynb
Follow current tutorial structure, show simple and slightly-less-simple queries, both with `.query` and with Python expressions.
Closes #672.
=> Improve the row-filtering tutorial.

src/lsdb/io/to_hats.py, tests/lsdb/io/test_to_hats.py
Reset the default columns for a catalog saved with `to_hats`, unless they are specified by the user. Closes #786.
=> Handle default columns in `to_hats`

src/lsdb/loaders/hats/read_hats.py, tests/lsdb/loaders/hats/test_read_hats.py
Allow columns to be anything array-like (e.g. list, tuple, series). Closes #807.
=> Accept array-like input for columns

src/lsdb/loaders/dataframe/dataframe_catalog_loader.py, tests/lsdb/loaders/dataframe/test_from_dataframe.py
Well this was a funky problem.
Prior to the hipscat->HATS renaming, we explicitly checked for two valid catalog types, OBJECT and SOURCE. During that transition, we started using `TableProperties`, instead of the `catalog_info.json`. Construction of the `TableProperties` checked that all of the type-specific kwargs were provided, and also that we **weren't** providing values for certain properties that were invalid for that catalog type (and to try to check for typos). The check inside `TableProperties` was what was preventing an ASSOCIATION (or MARGIN, or INDEX, or MAP) type from being created, as it was either missing required fields, or contained invalid fields.
PR https://github.com/astronomy-commons/hats/pull/511 removed that last bit of logic to allow any property keys (even ones …
=> Address smoke test failure.

src/lsdb/catalog/dataset/dataset.py, tests/lsdb/catalog/test_catalog.py
Change the representation of a dataset to say:
"X out of Y available columns in the catalog have been loaded"
rather than simply
"X out of Y columns in the catalog have been loaded"
The latter utterance implies to some users that those columns are known but never were imported.
=> Mention available columns

src/lsdb/core/crossmatch/crossmatch.py, src/lsdb/loaders/dataframe/dataframe_catalog_loader.py, src/lsdb/loaders/dataframe/from_dataframe.py, tests/lsdb/core/test_crossmatch_method.py, tests/lsdb/loaders/dataframe/test_from_dataframe.py
Find case-insensitive ra/dec columns in `from_dataframe` if they were not specified by the user. Closes #889.
=> Find ra/dec columns in `from_dataframe`

src/lsdb/core/crossmatch/crossmatch_algorithms.py, tests/lsdb/core/test_crossmatch_function.py
It should fix problems with `crossmatch(radius_arcsec=larger_than_five)`
=> Change is_builtin_algorithm to accept enum variants

pyproject.toml
This adds explicit dependency on the upath package, which 
a) is used by this package (not just a transitive dependency)
b) adds a minimum supported version
=> Make upath dependency very explicit.

src/lsdb/catalog/catalog.py, src/lsdb/core/search/index_search.py, tests/lsdb/catalog/test_index_search.py
=> Add option to input a list of values to id_search

src/lsdb/catalog/dataset/healpix_dataset.py, src/lsdb/core/search/cone_search.py, tests/lsdb/catalog/test_catalog.py
Closes #938 
Additional changes in this PR address pre-existing linting issues.
=> Rewrite cone_filter to not use astropy

src/lsdb/loaders/hats/read_hats.py
In working with the Zubercal dataset, users were running into issues with a memory leak during the `read_pixel` dask task. This led to workflows failing due to running out of memory. This change updates the `read_hats` behavior to avoid passing the `hats` `Catalog` object to the dask task graph, which seems to solve the memory leak problem.
My best guess is that the MOC object that is part of the hats Catalog could be causing this, since we've ran into issues with how they are cloud pickled before and how the Rust interaction works in dask distributed, but further investigation is necessary to confirm this.
=> Change `read_pixels` to avoid passing `HATS Catalog` object to dask graph

pyproject.toml
The length of the array is 103, while the length of the index is 101. This is some kind of subtle regression in pyarrow v21.0.0 that I haven't been able to pinpoint exactly.
Closes #974
=> Regression in windows pyarrow for chunked array

pyproject.toml, tests/lsdb/catalog/test_catalog.py
Noticing issues in another PR I'm working on with intermittent failures of the windows workflow with errors like:
```
FAILED tests/lsdb/catalog/test_catalog.py::test_plot_points_wcs - _tkinter.TclError: Can't find a usable init.tcl in the following directories: 
{C:\hostedtoolcache\windows\Python\3.10.11\x64\tcl\tcl8.6}
C:/hostedtoolcache/windows/Python/3.10.11/x64/tcl/tcl8.6/init.tcl: couldn't read file "C:/hostedtoolcache/windows/Python/3.10.11/x64/tcl/tcl8.6/init.tcl": No error
couldn't read file "C:/hostedtoolcache/windows/Python/3.10.11/x64/tcl/tcl8.6/init.tcl": No error
while executing
"source C:/hostedtoolcache/windows/Python/3.10.11/x64/tcl/tcl8.6/init.tcl"
("uplevel" body line 1)
invoked from within
"uplevel #0 [list source $tclfile]"
This probably means that Tcl wasn't installed …
```
=> Don't really plot images in unit tests

.github/dependabot.yml, pyproject.toml
Added notes regarding package version pinning for pyarrow and universal-pathlib, to help future maintainers avoid waving through mistaken dependabot suggestions.
=> Add version pinning notes for dependencies
