astronomy-commons/lsdb

.copier-answers.yml
.github/workflows/asv-pr.yml
.github/workflows/build-documentation.yml
.github/workflows/linting.yml
.github/workflows/pre-commit-ci.yml
.github/workflows/type-checking.yml
.gitignore
.pre-commit-config.yaml
docs/index.rst
pyproject.toml
src/.pylintrc
tests/.pylintrc

Updates uses the latest version of PPT from main

Update to latest PPT version

---

src/lsdb/catalog/catalog.py
src/lsdb/core/cone_search.py
tests/lsdb/catalog/test_cone_search.py

Adds a cone search function to the catalog that filters the catalog to the points within the specified cone, and filters the catalog's partitions to those that only overlap with the cone.

Add Cone Search to Catalog

---

src/lsdb/dask/crossmatch_catalog_data.py

Changes a filtering operation to use GTE instead of GT.

Fix crossmatch incorrectly filtering points at pixel boundary.

---

.github/workflows/linting.yml
tests/.pylintrc
tests/conftest.py
tests/lsdb/catalog/test_cone_search.py
tests/lsdb/catalog/test_crossmatch.py

See https://github.com/astronomy-commons/hipscat/pull/146 for similar issues in the hipscat repo.

Address pylint issues under /tests/

---

.github/workflows/smoke-test.yml
.github/workflows/testing-and-coverage.yml
.github/workflows/type-checking.yml

Remove 3.8 support

---

.copier-answers.yml
.github/workflows/asv-main.yml
.github/workflows/asv-nightly.yml

Runs copier update to patch the asv workflows that have been failing.

Run copier to patch workflows

---

src/lsdb/loaders/dataframe/dataframe_catalog_loader.py
tests/lsdb/loaders/dataframe/test_from_dataframe.py

Fix index not being set correctly in `from_dataframe`

---

benchmarks/benchmarks.py
benchmarks/utils.py

Adds benchmark for current polygonal search implementation.

Add benchmark for polygonal search

---

.copier-answers.yml
.git_archival.txt
.gitattributes
docs/conf.py
docs/requirements.txt
pyproject.toml
src/.pylintrc
tests/.pylintrc

See [release notes](https://github.com/lincc-frameworks/python-project-template/releases/tag/v1.4.6) for updates.

Apply template v.1.4.6

---

src/lsdb/core/crossmatch/kdtree_match.py
tests/lsdb/catalog/test_crossmatch.py

Changes default crossmatch maximum distance from 0.01 degrees, to 1 arc second
closes #128

Change default crossmatch radius

---

.copier-answers.yml
.github/workflows/pre-commit-ci.yml
.pre-commit-config.yaml
docs/conf.py
docs/index.rst
docs/requirements.txt

Mechanical application of copier update.

Apply PPT 1.5.3

---

docs/index.rst

Co-authored-by: Lovro Palaversa <lp@irb.hr>

Fix installation errors

---

pyproject.toml
src/lsdb/catalog/catalog.py
src/lsdb/core/search/cone_search.py
tests/lsdb/catalog/test_catalog.py
tests/lsdb/catalog/test_cone_search.py

Related to https://github.com/astronomy-commons/hipscat/issues/201

Change cone search argument to radius_arcsec

---

src/lsdb/catalog/catalog.py
src/lsdb/catalog/dataset/dataset.py
src/lsdb/catalog/dataset/healpix_dataset.py
tests/conftest.py
tests/lsdb/catalog/test_catalog.py

Refactors some `Catalog` methods to the `HealpixDataset` class, and updates the `query` Catalog method to also apply to the margin.

Query method updates margin catalog

---

tests/lsdb/catalog/test_catalog.py

Add test that we can handle pathlib.Path

---

benchmarks/benchmarks.py
requirements.txt
src/lsdb/core/search/box_search.py
src/lsdb/core/search/polygon_search.py

Follow-up pull request for changes in https://github.com/astronomy-commons/hipscat/pull/224.

Add box filter benchmark on partition

---

docs/notebooks/import_catalogs.ipynb
docs/requirements.txt
src/lsdb/catalog/catalog.py
src/lsdb/catalog/dataset/dataset.py
src/lsdb/catalog/dataset/healpix_dataset.py
src/lsdb/core/search/abstract_search.py
src/lsdb/dask/crossmatch_catalog_data.py
src/lsdb/dask/join_catalog_data.py
src/lsdb/dask/merge_catalog_functions.py
src/lsdb/loaders/dataframe/margin_catalog_generator.py
src/lsdb/loaders/hipscat/read_hipscat.py

Closes #167 
- requires ipywidgets for improved tqdm rendering
- simplifies some other output for import notebook
- fixes some docstrings that weren't rendering well on readthedocs.

Documentation improvements

---

docs/conf.py
docs/requirements.txt

Updates the sphinx theme to use [book theme](https://sphinx-book-theme.readthedocs.io/en/stable/index.html).

Change sphinx theme

---

docs/_static/custom.css
docs/conf.py

Changes text color to render lighter in dark mode

fix notebook tqdm rendering

---

docs/gettingstarted.rst
docs/gettingstarted/contributing.rst
docs/gettingstarted/installation.rst
docs/index.rst

Add a brief description of LSDB to the landing page and create a scaffold for the contribution guide. Closes #254.

Polish landing page

---

.copier-answers.yml

Update PPT version

---

README.md

updates acknowledgement to Schmidt sciences

Update readme acknowledgement

---

README.md

Fixes link to contribution getting started in readme

Update getting started link README

---

tests/lsdb/catalog/test_polygon_search.py
tests/lsdb/loaders/dataframe/test_from_dataframe.py

Changes to the pixel tree behavior needs changes to unit tests in LSDB

Update unit tests for interval pixel tree

---

src/lsdb/catalog/dataset/healpix_dataset.py
src/lsdb/core/plotting/skymap.py
tests/lsdb/catalog/test_catalog.py
tests/lsdb/core/test_kdtree_validation.py

Changes vectorized filtering to a groupby. Fixes #266

Optimize skymap at high fixed order

---

docs/developer/contributing.rst

Adds detailed instructions on how external collaborators can contribute to the LSDB repository. Closes #241.

Improve contribution guide

---

README.md
docs/index.rst

Augment acknowledgement and add to RTD.

Update acknowledgment text

---

.github/workflows/smoke-test.yml
.github/workflows/testing-and-coverage.yml
pyproject.toml

Update python and hipscat version pins.

---

.github/workflows/smoke-test.yml
.github/workflows/testing-and-coverage.yml
pyproject.toml
src/lsdb/catalog/dataset/dataset.py
src/lsdb/catalog/dataset/healpix_dataset.py
src/lsdb/dask/crossmatch_catalog_data.py
src/lsdb/dask/join_catalog_data.py
src/lsdb/dask/merge_catalog_functions.py
src/lsdb/loaders/dataframe/from_dataframe_utils.py
src/lsdb/loaders/dataframe/margin_catalog_generator.py
src/lsdb/loaders/hipscat/association_catalog_loader.py
tests/conftest.py
tests/lsdb/catalog/test_association_catalog.py

After more testing on larger datasets, there are performance issues with dask expressions and lsdb, so this reverts the changes introduced in #288

Revert dask expressions

---

src/lsdb/core/crossmatch/abstract_crossmatch_algorithm.py
src/lsdb/core/crossmatch/bounded_kdtree_match.py
src/lsdb/core/crossmatch/kdtree_match.py
tests/lsdb/catalog/test_crossmatch.py

Remove **kwargs from crossmatching algorithms methods

---

src/lsdb/core/crossmatch/kdtree_utils.py
tests/lsdb/catalog/test_crossmatch.py

Fix empty right catalog error in cross-matching

---

src/lsdb/catalog/association_catalog.py
src/lsdb/catalog/catalog.py
src/lsdb/catalog/dataset/dataset.py
src/lsdb/catalog/dataset/healpix_dataset.py
src/lsdb/catalog/margin_catalog.py
src/lsdb/core/search/box_search.py
src/lsdb/core/search/cone_search.py
src/lsdb/core/search/polygon_search.py
src/lsdb/dask/crossmatch_catalog_data.py
src/lsdb/dask/join_catalog_data.py
src/lsdb/dask/merge_catalog_functions.py
src/lsdb/loaders/dataframe/dataframe_catalog_loader.py
src/lsdb/loaders/dataframe/from_dataframe_utils.py
src/lsdb/loaders/dataframe/margin_catalog_generator.py
src/lsdb/loaders/hipscat/abstract_catalog_loader.py
src/lsdb/loaders/hipscat/association_catalog_loader.py
tests/conftest.py
tests/lsdb/catalog/test_association_catalog.py
tests/lsdb/catalog/test_catalog.py
tests/lsdb/catalog/test_merge.py

Updates dask DataFrame calls to use expressions methods instead of legacy methods. Updates DataFrame creation methods to check for empty delayed lists which now fail with dask expressions. Updates search to use map_partitions instead of delayed for better performance.

Change to using dask expressions

---

docs/developer/contributing.rst
docs/tutorials/getting_data.ipynb

"Getting data into LSDB" should include a reference to the import topic

---

src/lsdb/catalog/dataset/healpix_dataset.py
tests/lsdb/catalog/test_catalog.py

Adds plot_moc method to catalog

Add plot moc method

---

.github/ISSUE_TEMPLATE/4-release_tracker.md

First pass on release checklist.

Add issue template for release tracking

---

src/lsdb/loaders/dataframe/dataframe_catalog_loader.py
src/lsdb/loaders/dataframe/from_dataframe.py

Remove in csv format in docstring for from_dataframe

---

src/lsdb/dask/crossmatch_catalog_data.py
src/lsdb/dask/join_catalog_data.py
src/lsdb/dask/merge_catalog_functions.py
src/lsdb/dask/merge_map_catalog_data.py
tests/conftest.py
tests/lsdb/catalog/test_join.py
tests/lsdb/catalog/test_nested.py

Fix hive columns not being updated during merge operations

---

docs/developer/contributing.rst
docs/tutorials.rst

`make html` was throwing warnings about all of these links.

Fix display of links and headers

---

docs/tutorials/filtering_large_catalogs.ipynb

Closes #593
- I added a "mean_mag_r" column when we call `lsdb.read_hats()`, as I felt that filtering columns by ra/dec would be conceptually too similar to the spatial filtering section just before
- Took my best stab at descriptive text, open to suggestions/revisions

Add filter by column query section

---

tests/lsdb/catalog/test_join.py

This method was tricky to debug in something else I'm working on. Made much easier by not having tests inside a for-loop.

Parametrize test instead of for loop.

---

src/lsdb/core/search/cone_search.py
tests/lsdb/catalog/test_cone_search.py

Fix plotting defaults

---

src/lsdb/loaders/hats/read_hats.py
tests/lsdb/loaders/hats/test_read_hats.py

Fixes error in unit tests from recent changes to empty catalog filtering in hats

fix reading behaviour with new hats changes

---

requirements.txt

This will help using this file with `uv pip compile --constraint=requirement.txt`

Give names to deps in requirements.txt

---

src/lsdb/nested/backends.py

remove 3.9 handling in lsdb.nested backend

---

pyproject.toml

For https://github.com/astronomy-commons/lsdb/issues/751

Require newest hats version.

---

src/lsdb/catalog/dataset/healpix_dataset.py
tests/lsdb/catalog/test_nested.py

add nested_columns property to catalog

---

docs/tutorials/region_selection.ipynb

Closes #778
Totally ok with moving this elsewhere in the notebook (or to a different nb)—would just like some mention of it somewhere

Add brief note for tract-patch search and link to lsdb-rubin

---

docs/conf.py

Changes 2024 to 2025 in the copyright notice in the documentation

2024 to 2025 in docs

---

pyproject.toml

update nested-pandas pin

---

docs/getting-started.rst

Modifies the description of when you need to use [full] installation. Based on the suggestion by @sbailey

Modify text with [full] install

---

src/lsdb/loaders/hats/read_hats.py
tests/lsdb/loaders/hats/test_read_hats.py

include ra and dec columns if they're not in the specified columns or default_columns when loading a catalog
Closes #556

include ra and dec columns

---

docs/getting-started.rst
docs/tutorials/pre_executed/crossmatching.ipynb
docs/tutorials/pre_executed/join_catalogs.ipynb

Recommend filters on opening, add references, correct some parameters

Tidy up the getting-started page

---

src/lsdb/catalog/catalog.py
src/lsdb/catalog/dataset/dataset.py
src/lsdb/catalog/dataset/healpix_dataset.py
src/lsdb/io/to_association.py
src/lsdb/io/to_hats.py
src/lsdb/loaders/hats/read_hats.py
src/lsdb/nested/datasets/generation.py

With changes in PR #853 , it's easier to read through individual property and method API docs. And it's easier to see where they need to be spruced up!

Docstring cleanups

---

docs/tutorial_toc/toc_rubin.rst

Accidentally removed the link to the photo-z nb

fix bad toc conflict resolution

---

src/lsdb/catalog/catalog.py
src/lsdb/catalog/dataset/healpix_dataset.py
src/lsdb/nested/core.py
tests/lsdb/catalog/test_catalog.py

Support the pandas rename function with the column argument in Catalog. Overrides HealpixDataset.rename() which calls NestedFrame.rename().
Closes #433

add Catalog.rename()

---

docs/index.rst

Make Citation more prominent on the webpage. Hotfix before better solution is created.

citation more prominent on web

---

docs/tutorials/pre_executed/rubin_dp1.ipynb

Remove date for Rubin on CANFAR

remove date for Rubin on CANFAR

---

docs/contact.rst
docs/tutorials/pre_executed/rubin_dp1.ipynb
docs/tutorials/region_selection.ipynb

Introduce and encourage LSST Community forum.

---

docs/tutorials/pre_executed/rubin_dp1.ipynb

Add proper warning markdown to the soft launch period

Add proper warning markdown

---

docs/tutorials/pre_executed/rubin_dp1.ipynb

Closes https://github.com/astronomy-commons/lsdb/issues/922

Docs: DP1 NERSC instructions

---

docs/tutorials/pre_executed/rubin_dp1.ipynb

Remove soft launch warnings in the accessing dp1 documentation

Remove soft launch warnings

---

src/lsdb/io/to_association.py
tests/lsdb/io/test_to_association.py

Prevent writing empty leaf files for associations

---

pyproject.toml

https://github.com/astronomy-commons/lsdb/issues/990

Release: v0.6.4

---

docs/tutorials/region_selection.ipynb
src/lsdb/core/search/box_search.py

Add section on region search on complex MOC filters.

---

requirements.txt

See also: https://github.com/astronomy-commons/hats-cloudtests/pull/92

Use released nested-pandas (for now)

---

.github/ISSUE_TEMPLATE/4-release_tracker.md

Add release stage to check RSP environment changes

---

pyproject.toml

Reverts astronomy-commons/lsdb#1053
See also #1020

Revert "Update pyarrow requirement from <21.0.0,>=14.0.1 to >=14.0.1,<22.0.0"
